/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WellnessRouteImport } from './routes/wellness'
import { Route as UnsubscribeRouteImport } from './routes/unsubscribe'
import { Route as TrainingRouteImport } from './routes/training'
import { Route as SupplementsRouteImport } from './routes/supplements'
import { Route as SuccessRouteImport } from './routes/success'
import { Route as SpeakingRouteImport } from './routes/speaking'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as ProgramsRouteImport } from './routes/programs'
import { Route as PhilosophyRouteImport } from './routes/philosophy'
import { Route as MerchRouteImport } from './routes/merch'
import { Route as ManualsRouteImport } from './routes/manuals'
import { Route as FstRouteImport } from './routes/fst'
import { Route as EvaluationRouteImport } from './routes/evaluation'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as CollectionRouteImport } from './routes/collection'
import { Route as CoachingRouteImport } from './routes/coaching'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CancelRouteImport } from './routes/cancel'
import { Route as BookRouteImport } from './routes/book'
import { Route as AdvocacyRouteImport } from './routes/advocacy'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EliteIndexRouteImport } from './routes/elite.index'
import { Route as ShopSlugRouteImport } from './routes/shop.$slug'
import { Route as EmailUnsubscribeRouteImport } from './routes/email/unsubscribe'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as EliteLearnIndexRouteImport } from './routes/elite.learn.index'
import { Route as LovableEmailSuppressionRouteImport } from './routes/lovable/email/suppression'
import { Route as EliteLearnLessonRouteImport } from './routes/elite.learn.$lesson'
import { Route as ApiPublicStripeWebhookRouteImport } from './routes/api/public/stripe-webhook'
import { Route as LovableEmailTransactionalSendRouteImport } from './routes/lovable/email/transactional/send'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'

const WellnessRoute = WellnessRouteImport.update({
  id: '/wellness',
  path: '/wellness',
  getParentRoute: () => rootRouteImport,
} as any)
const UnsubscribeRoute = UnsubscribeRouteImport.update({
  id: '/unsubscribe',
  path: '/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainingRoute = TrainingRouteImport.update({
  id: '/training',
  path: '/training',
  getParentRoute: () => rootRouteImport,
} as any)
const SupplementsRoute = SupplementsRouteImport.update({
  id: '/supplements',
  path: '/supplements',
  getParentRoute: () => rootRouteImport,
} as any)
const SuccessRoute = SuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => rootRouteImport,
} as any)
const SpeakingRoute = SpeakingRouteImport.update({
  id: '/speaking',
  path: '/speaking',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsRoute = ProgramsRouteImport.update({
  id: '/programs',
  path: '/programs',
  getParentRoute: () => rootRouteImport,
} as any)
const PhilosophyRoute = PhilosophyRouteImport.update({
  id: '/philosophy',
  path: '/philosophy',
  getParentRoute: () => rootRouteImport,
} as any)
const MerchRoute = MerchRouteImport.update({
  id: '/merch',
  path: '/merch',
  getParentRoute: () => rootRouteImport,
} as any)
const ManualsRoute = ManualsRouteImport.update({
  id: '/manuals',
  path: '/manuals',
  getParentRoute: () => rootRouteImport,
} as any)
const FstRoute = FstRouteImport.update({
  id: '/fst',
  path: '/fst',
  getParentRoute: () => rootRouteImport,
} as any)
const EvaluationRoute = EvaluationRouteImport.update({
  id: '/evaluation',
  path: '/evaluation',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionRoute = CollectionRouteImport.update({
  id: '/collection',
  path: '/collection',
  getParentRoute: () => rootRouteImport,
} as any)
const CoachingRoute = CoachingRouteImport.update({
  id: '/coaching',
  path: '/coaching',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CancelRoute = CancelRouteImport.update({
  id: '/cancel',
  path: '/cancel',
  getParentRoute: () => rootRouteImport,
} as any)
const BookRoute = BookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => rootRouteImport,
} as any)
const AdvocacyRoute = AdvocacyRouteImport.update({
  id: '/advocacy',
  path: '/advocacy',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EliteIndexRoute = EliteIndexRouteImport.update({
  id: '/elite/',
  path: '/elite/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopSlugRoute = ShopSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ShopRoute,
} as any)
const EmailUnsubscribeRoute = EmailUnsubscribeRouteImport.update({
  id: '/email/unsubscribe',
  path: '/email/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const EliteLearnIndexRoute = EliteLearnIndexRouteImport.update({
  id: '/elite/learn/',
  path: '/elite/learn/',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailSuppressionRoute = LovableEmailSuppressionRouteImport.update({
  id: '/lovable/email/suppression',
  path: '/lovable/email/suppression',
  getParentRoute: () => rootRouteImport,
} as any)
const EliteLearnLessonRoute = EliteLearnLessonRouteImport.update({
  id: '/elite/learn/$lesson',
  path: '/elite/learn/$lesson',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicStripeWebhookRoute = ApiPublicStripeWebhookRouteImport.update({
  id: '/api/public/stripe-webhook',
  path: '/api/public/stripe-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailTransactionalSendRoute =
  LovableEmailTransactionalSendRouteImport.update({
    id: '/lovable/email/transactional/send',
    path: '/lovable/email/transactional/send',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/advocacy': typeof AdvocacyRoute
  '/book': typeof BookRoute
  '/cancel': typeof CancelRoute
  '/checkout': typeof CheckoutRoute
  '/coaching': typeof CoachingRoute
  '/collection': typeof CollectionRoute
  '/community': typeof CommunityRoute
  '/contact': typeof ContactRoute
  '/evaluation': typeof EvaluationRoute
  '/fst': typeof FstRoute
  '/manuals': typeof ManualsRoute
  '/merch': typeof MerchRoute
  '/philosophy': typeof PhilosophyRoute
  '/programs': typeof ProgramsRoute
  '/shop': typeof ShopRouteWithChildren
  '/speaking': typeof SpeakingRoute
  '/success': typeof SuccessRoute
  '/supplements': typeof SupplementsRoute
  '/training': typeof TrainingRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/wellness': typeof WellnessRoute
  '/api/chat': typeof ApiChatRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/shop/$slug': typeof ShopSlugRoute
  '/elite/': typeof EliteIndexRoute
  '/api/public/stripe-webhook': typeof ApiPublicStripeWebhookRoute
  '/elite/learn/$lesson': typeof EliteLearnLessonRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/elite/learn/': typeof EliteLearnIndexRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/advocacy': typeof AdvocacyRoute
  '/book': typeof BookRoute
  '/cancel': typeof CancelRoute
  '/checkout': typeof CheckoutRoute
  '/coaching': typeof CoachingRoute
  '/collection': typeof CollectionRoute
  '/community': typeof CommunityRoute
  '/contact': typeof ContactRoute
  '/evaluation': typeof EvaluationRoute
  '/fst': typeof FstRoute
  '/manuals': typeof ManualsRoute
  '/merch': typeof MerchRoute
  '/philosophy': typeof PhilosophyRoute
  '/programs': typeof ProgramsRoute
  '/shop': typeof ShopRouteWithChildren
  '/speaking': typeof SpeakingRoute
  '/success': typeof SuccessRoute
  '/supplements': typeof SupplementsRoute
  '/training': typeof TrainingRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/wellness': typeof WellnessRoute
  '/api/chat': typeof ApiChatRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/shop/$slug': typeof ShopSlugRoute
  '/elite': typeof EliteIndexRoute
  '/api/public/stripe-webhook': typeof ApiPublicStripeWebhookRoute
  '/elite/learn/$lesson': typeof EliteLearnLessonRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/elite/learn': typeof EliteLearnIndexRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/advocacy': typeof AdvocacyRoute
  '/book': typeof BookRoute
  '/cancel': typeof CancelRoute
  '/checkout': typeof CheckoutRoute
  '/coaching': typeof CoachingRoute
  '/collection': typeof CollectionRoute
  '/community': typeof CommunityRoute
  '/contact': typeof ContactRoute
  '/evaluation': typeof EvaluationRoute
  '/fst': typeof FstRoute
  '/manuals': typeof ManualsRoute
  '/merch': typeof MerchRoute
  '/philosophy': typeof PhilosophyRoute
  '/programs': typeof ProgramsRoute
  '/shop': typeof ShopRouteWithChildren
  '/speaking': typeof SpeakingRoute
  '/success': typeof SuccessRoute
  '/supplements': typeof SupplementsRoute
  '/training': typeof TrainingRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/wellness': typeof WellnessRoute
  '/api/chat': typeof ApiChatRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/shop/$slug': typeof ShopSlugRoute
  '/elite/': typeof EliteIndexRoute
  '/api/public/stripe-webhook': typeof ApiPublicStripeWebhookRoute
  '/elite/learn/$lesson': typeof EliteLearnLessonRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/elite/learn/': typeof EliteLearnIndexRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/advocacy'
    | '/book'
    | '/cancel'
    | '/checkout'
    | '/coaching'
    | '/collection'
    | '/community'
    | '/contact'
    | '/evaluation'
    | '/fst'
    | '/manuals'
    | '/merch'
    | '/philosophy'
    | '/programs'
    | '/shop'
    | '/speaking'
    | '/success'
    | '/supplements'
    | '/training'
    | '/unsubscribe'
    | '/wellness'
    | '/api/chat'
    | '/email/unsubscribe'
    | '/shop/$slug'
    | '/elite/'
    | '/api/public/stripe-webhook'
    | '/elite/learn/$lesson'
    | '/lovable/email/suppression'
    | '/elite/learn/'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/advocacy'
    | '/book'
    | '/cancel'
    | '/checkout'
    | '/coaching'
    | '/collection'
    | '/community'
    | '/contact'
    | '/evaluation'
    | '/fst'
    | '/manuals'
    | '/merch'
    | '/philosophy'
    | '/programs'
    | '/shop'
    | '/speaking'
    | '/success'
    | '/supplements'
    | '/training'
    | '/unsubscribe'
    | '/wellness'
    | '/api/chat'
    | '/email/unsubscribe'
    | '/shop/$slug'
    | '/elite'
    | '/api/public/stripe-webhook'
    | '/elite/learn/$lesson'
    | '/lovable/email/suppression'
    | '/elite/learn'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/advocacy'
    | '/book'
    | '/cancel'
    | '/checkout'
    | '/coaching'
    | '/collection'
    | '/community'
    | '/contact'
    | '/evaluation'
    | '/fst'
    | '/manuals'
    | '/merch'
    | '/philosophy'
    | '/programs'
    | '/shop'
    | '/speaking'
    | '/success'
    | '/supplements'
    | '/training'
    | '/unsubscribe'
    | '/wellness'
    | '/api/chat'
    | '/email/unsubscribe'
    | '/shop/$slug'
    | '/elite/'
    | '/api/public/stripe-webhook'
    | '/elite/learn/$lesson'
    | '/lovable/email/suppression'
    | '/elite/learn/'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdvocacyRoute: typeof AdvocacyRoute
  BookRoute: typeof BookRoute
  CancelRoute: typeof CancelRoute
  CheckoutRoute: typeof CheckoutRoute
  CoachingRoute: typeof CoachingRoute
  CollectionRoute: typeof CollectionRoute
  CommunityRoute: typeof CommunityRoute
  ContactRoute: typeof ContactRoute
  EvaluationRoute: typeof EvaluationRoute
  FstRoute: typeof FstRoute
  ManualsRoute: typeof ManualsRoute
  MerchRoute: typeof MerchRoute
  PhilosophyRoute: typeof PhilosophyRoute
  ProgramsRoute: typeof ProgramsRoute
  ShopRoute: typeof ShopRouteWithChildren
  SpeakingRoute: typeof SpeakingRoute
  SuccessRoute: typeof SuccessRoute
  SupplementsRoute: typeof SupplementsRoute
  TrainingRoute: typeof TrainingRoute
  UnsubscribeRoute: typeof UnsubscribeRoute
  WellnessRoute: typeof WellnessRoute
  ApiChatRoute: typeof ApiChatRoute
  EmailUnsubscribeRoute: typeof EmailUnsubscribeRoute
  EliteIndexRoute: typeof EliteIndexRoute
  ApiPublicStripeWebhookRoute: typeof ApiPublicStripeWebhookRoute
  EliteLearnLessonRoute: typeof EliteLearnLessonRoute
  LovableEmailSuppressionRoute: typeof LovableEmailSuppressionRoute
  EliteLearnIndexRoute: typeof EliteLearnIndexRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
  LovableEmailTransactionalSendRoute: typeof LovableEmailTransactionalSendRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wellness': {
      id: '/wellness'
      path: '/wellness'
      fullPath: '/wellness'
      preLoaderRoute: typeof WellnessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unsubscribe': {
      id: '/unsubscribe'
      path: '/unsubscribe'
      fullPath: '/unsubscribe'
      preLoaderRoute: typeof UnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/training': {
      id: '/training'
      path: '/training'
      fullPath: '/training'
      preLoaderRoute: typeof TrainingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/supplements': {
      id: '/supplements'
      path: '/supplements'
      fullPath: '/supplements'
      preLoaderRoute: typeof SupplementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/success': {
      id: '/success'
      path: '/success'
      fullPath: '/success'
      preLoaderRoute: typeof SuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/speaking': {
      id: '/speaking'
      path: '/speaking'
      fullPath: '/speaking'
      preLoaderRoute: typeof SpeakingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs': {
      id: '/programs'
      path: '/programs'
      fullPath: '/programs'
      preLoaderRoute: typeof ProgramsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/philosophy': {
      id: '/philosophy'
      path: '/philosophy'
      fullPath: '/philosophy'
      preLoaderRoute: typeof PhilosophyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/merch': {
      id: '/merch'
      path: '/merch'
      fullPath: '/merch'
      preLoaderRoute: typeof MerchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manuals': {
      id: '/manuals'
      path: '/manuals'
      fullPath: '/manuals'
      preLoaderRoute: typeof ManualsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fst': {
      id: '/fst'
      path: '/fst'
      fullPath: '/fst'
      preLoaderRoute: typeof FstRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evaluation': {
      id: '/evaluation'
      path: '/evaluation'
      fullPath: '/evaluation'
      preLoaderRoute: typeof EvaluationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collection': {
      id: '/collection'
      path: '/collection'
      fullPath: '/collection'
      preLoaderRoute: typeof CollectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coaching': {
      id: '/coaching'
      path: '/coaching'
      fullPath: '/coaching'
      preLoaderRoute: typeof CoachingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cancel': {
      id: '/cancel'
      path: '/cancel'
      fullPath: '/cancel'
      preLoaderRoute: typeof CancelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book': {
      id: '/book'
      path: '/book'
      fullPath: '/book'
      preLoaderRoute: typeof BookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/advocacy': {
      id: '/advocacy'
      path: '/advocacy'
      fullPath: '/advocacy'
      preLoaderRoute: typeof AdvocacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/elite/': {
      id: '/elite/'
      path: '/elite'
      fullPath: '/elite/'
      preLoaderRoute: typeof EliteIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/$slug': {
      id: '/shop/$slug'
      path: '/$slug'
      fullPath: '/shop/$slug'
      preLoaderRoute: typeof ShopSlugRouteImport
      parentRoute: typeof ShopRoute
    }
    '/email/unsubscribe': {
      id: '/email/unsubscribe'
      path: '/email/unsubscribe'
      fullPath: '/email/unsubscribe'
      preLoaderRoute: typeof EmailUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/elite/learn/': {
      id: '/elite/learn/'
      path: '/elite/learn'
      fullPath: '/elite/learn/'
      preLoaderRoute: typeof EliteLearnIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/suppression': {
      id: '/lovable/email/suppression'
      path: '/lovable/email/suppression'
      fullPath: '/lovable/email/suppression'
      preLoaderRoute: typeof LovableEmailSuppressionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/elite/learn/$lesson': {
      id: '/elite/learn/$lesson'
      path: '/elite/learn/$lesson'
      fullPath: '/elite/learn/$lesson'
      preLoaderRoute: typeof EliteLearnLessonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/stripe-webhook': {
      id: '/api/public/stripe-webhook'
      path: '/api/public/stripe-webhook'
      fullPath: '/api/public/stripe-webhook'
      preLoaderRoute: typeof ApiPublicStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/send': {
      id: '/lovable/email/transactional/send'
      path: '/lovable/email/transactional/send'
      fullPath: '/lovable/email/transactional/send'
      preLoaderRoute: typeof LovableEmailTransactionalSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ShopRouteChildren {
  ShopSlugRoute: typeof ShopSlugRoute
}

const ShopRouteChildren: ShopRouteChildren = {
  ShopSlugRoute: ShopSlugRoute,
}

const ShopRouteWithChildren = ShopRoute._addFileChildren(ShopRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdvocacyRoute: AdvocacyRoute,
  BookRoute: BookRoute,
  CancelRoute: CancelRoute,
  CheckoutRoute: CheckoutRoute,
  CoachingRoute: CoachingRoute,
  CollectionRoute: CollectionRoute,
  CommunityRoute: CommunityRoute,
  ContactRoute: ContactRoute,
  EvaluationRoute: EvaluationRoute,
  FstRoute: FstRoute,
  ManualsRoute: ManualsRoute,
  MerchRoute: MerchRoute,
  PhilosophyRoute: PhilosophyRoute,
  ProgramsRoute: ProgramsRoute,
  ShopRoute: ShopRouteWithChildren,
  SpeakingRoute: SpeakingRoute,
  SuccessRoute: SuccessRoute,
  SupplementsRoute: SupplementsRoute,
  TrainingRoute: TrainingRoute,
  UnsubscribeRoute: UnsubscribeRoute,
  WellnessRoute: WellnessRoute,
  ApiChatRoute: ApiChatRoute,
  EmailUnsubscribeRoute: EmailUnsubscribeRoute,
  EliteIndexRoute: EliteIndexRoute,
  ApiPublicStripeWebhookRoute: ApiPublicStripeWebhookRoute,
  EliteLearnLessonRoute: EliteLearnLessonRoute,
  LovableEmailSuppressionRoute: LovableEmailSuppressionRoute,
  EliteLearnIndexRoute: EliteLearnIndexRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
  LovableEmailTransactionalSendRoute: LovableEmailTransactionalSendRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
