INSERT INTO public.products (slug, name, tagline, description, price_cents, currency, image_url, sort_order, is_active) VALUES
  ('ooo-jersey-8', 'OOO #8 Game Jersey', 'Signature mesh basketball jersey.',
   E'Premium performance mesh with embroidered fist mark and #8 back print. Cut for on-court movement, built to wear anywhere.\n\nAvailable sizes: S, M, L, XL, XXL.\nShips in 5–7 business days.',
   12000, 'usd',
   '/__l5e/assets-v1/c0140d8b-3da2-40d8-a5ff-e2bd4fd6f8a3/ooo-merch_0.jpg', 10, true),
  ('ooo-track-jacket-onyx', 'OOO Track Jacket — Onyx', 'Full-zip warm-up with taped sleeves.',
   E'Structured onyx track jacket with piped seams and OOO taped sleeve detail. Cut for movement, built for the walk-in.\n\nAvailable sizes: S, M, L, XL, XXL.\nShips in 5–7 business days.',
   18500, 'usd',
   '/__l5e/assets-v1/62a6bf9e-05fb-4f0e-a2de-62b7546ab081/ooo-merch_1.jpg', 20, true),
  ('ooo-tracksuit-ivory', 'OOO Tracksuit — Ivory (Set)', 'Two-piece jacket + jogger set.',
   E'Ivory technical fleece set. Matching full-zip jacket and tapered jogger with OOO ring stripe down the leg. Sold as a set.\n\nAvailable sizes: S, M, L, XL, XXL.',
   29500, 'usd',
   '/__l5e/assets-v1/087f4d48-c99e-4518-8810-71c62f1fb34b/ooo-merch_2.jpg', 30, true),
  ('ooo-hoodie-ivory-black', 'OOO Contrast Hoodie — Ivory / Black', 'Heavyweight fleece, black-lined hood and pocket.',
   E'Heavyweight cotton fleece pullover. Ivory body, black hood lining, kangaroo pocket and cuffs. Embroidered OOO chest mark.\n\nAvailable sizes: S, M, L, XL, XXL.',
   13500, 'usd',
   '/__l5e/assets-v1/0d186108-65db-4319-9d8d-4f728d649d96/ooo-merch_3.jpg', 40, true),
  ('ooo-hoodie-split-hood', 'OOO Split Hood Hoodie — Ivory', 'Ivory body with black hood and cuffs.',
   E'Clean ivory pullover with black hood and cuff finish. Puff-print OOO chest mark.\n\nAvailable sizes: S, M, L, XL, XXL.',
   13500, 'usd',
   '/__l5e/assets-v1/685e2eb1-c95c-4919-9e43-339a4d841807/ooo-merch_4.jpg', 50, true),
  ('ooo-hoodie-black-ivory', 'OOO Contrast Hoodie — Black / Ivory', 'Heavyweight fleece, ivory hood and pocket.',
   E'Heavyweight cotton fleece pullover. Black body, ivory hood, cuffs and kangaroo pocket. Embroidered OOO chest mark.\n\nAvailable sizes: S, M, L, XL, XXL.',
   13500, 'usd',
   '/__l5e/assets-v1/271624df-200c-4547-8122-ed868d01b566/ooo-merch_5.jpg', 60, true),
  ('ooo-fleece-track-jacket', 'OOO Fleece Track Jacket', 'Full-zip fleece with arched back logo.',
   E'Brushed fleece full-zip. Chest OOO mark, arched "Of Our Own" back print.\n\nAvailable sizes: S, M, L, XL, XXL.\nColors: Ivory, Black — note preference at checkout.',
   17500, 'usd',
   '/__l5e/assets-v1/4a5c4f0d-a64f-433c-8b75-cd5eb019aa0c/ooo-merch_6.jpg', 70, true),
  ('ooo-fleece-snap-pullover', 'OOO Snap Fleece Pullover', 'Snap-placket sherpa-feel pullover.',
   E'Cozy snap-placket fleece pullover. Chest OOO stack, arched back print.\n\nAvailable sizes: S, M, L, XL, XXL.\nColors: Ivory, Black — note preference at checkout.',
   16500, 'usd',
   '/__l5e/assets-v1/9f73a817-02d4-41ce-8208-d83b12c76e09/ooo-merch_7.jpg', 80, true)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  tagline = EXCLUDED.tagline,
  description = EXCLUDED.description,
  price_cents = EXCLUDED.price_cents,
  image_url = EXCLUDED.image_url,
  sort_order = EXCLUDED.sort_order,
  is_active = true,
  updated_at = now();